version: '3.1'

services:
  arangodb_db_container:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
    ports:
      - 8529:8529
    volumes:
      - ./docker/arangodb_data_container:/var/lib/arangodb3
      - ./docker/arangodb_apps_data_container:/var/lib/arangodb3-apps