version: '3.1'

services:
  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@genericapi.com
      PGADMIN_DEFAULT_PASSWORD: password
#    volumes:
#      - ./database/.pgadmin:/var/lib/pgadmin
    networks:
      - postgres
  postgres:
    restart: always
    image: postgres
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=100'
      - '-c'
      - 'shared_buffers=256MB'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: generic_api
#    volumes:
#      - ./database/init_scripts:/docker-entrypoint-initdb.d/
#      - ./database/.data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres

networks:
  postgres:
    driver: bridge